---
- name: Pull OCR container images
  community.docker.docker_image_pull:
    name: "{{ ocr_container_image }}"
    platform: amd64
  loop: "{{ ocr_container_images }}"
  loop_control:
    loop_var: ocr_container_image
    label: "{{ ocr_container_image }}"
