---
- name: Check {{ quarto_install_dir }} path
  ansible.builtin.stat:
    path: "{{ quarto_install_dir }}"
  register: path_stat

- name: Remove {{ quarto_install_dir }} if it exists as a directory
  ansible.builtin.file:
    path: "{{ quarto_install_dir }}"
    state: absent
  when: path_stat.stat.exists and path_stat.stat.isdir
  register: remove_result

- block:
    - name: Download Quarto tarball
      ansible.builtin.get_url:
        url: "{{ quarto_url }}"
        dest: "/tmp/{{ quarto_tarball }}"
        mode: "0644"

    - name: Unpack Quarto tarball to {{ quarto_install_dir }}-{{ quarto_version }}
      ansible.builtin.unarchive:
        src: "/tmp/{{ quarto_tarball }}"
        dest: /opt
        remote_src: true
  when: not path_stat.stat.exists or remove_result.changed

- name: Symlink {{ quarto_install_dir }} -> {{ quarto_install_dir }}-{{ quarto_version }}
  ansible.builtin.file:
    src: "{{ quarto_install_dir }}-{{ quarto_version }}"
    dest: "{{ quarto_install_dir }}"
    state: link
    force: true
    follow: false

- name: Add {{ quarto_install_dir }}/bin to system PATH
  ansible.builtin.copy:
    dest: /etc/profile.d/quarto.sh
    mode: "0644"
    content: |
      export PATH={{ quarto_install_dir }}/bin:$PATH
