---
- name: Install required baseline packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ baseline_required_packages }}"

- name: Install optional baseline packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ baseline_optional_packages }}"
