---

- name: Install Nemo
  ansible.builtin.dnf:
    name: "{{ nemo_packages }}"
    state: present
  when: nemo_packages | length > 0

- name: Remove obsolete Nemo packages
  ansible.builtin.dnf:
    name: "{{ nemo_obsolete_packages }}"
    state: absent
  when: nemo_obsolete_packages | length > 0
