---
- name: Enable RPM Fusion free and nonfree repository
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    disable_gpg_check: true
  loop: "{{ rpmfusion_urls }}"
  when: ansible_facts['distribution'] == 'Fedora'
