---
baseline_base_packages:
  - ca-certificates
  - curl
  - dnf-plugins-core
  - git
  - python3
  - python3-pip
  - tar
  - unzip
  - wget

baseline_remove_packages_best_effort:
  - aisleriot
  - brasero
  - cheese
  - deja-dup
  - evolution
  - evince
  - gnome-boxes
  - gnome-calendar
  - gnome-characters
  - gnome-connections
  - gnome-contacts
  - gnome-font-viewer
  - gnome-mahjongg
  - gnome-maps
  - gnome-mines
  - gnome-sudoku
  - gnome-todo
  - gnome-tour
  - gnome-weather
  - ibus-m17n
  - ibus-typing-booster
  - malcontent
  - malcontent-control
  - mediawriter
  - nautilus-share
  - orca
  - shotwell
  - simple-scan
  - telnet
  - transmission
  - vino
  - yelp

baseline_install_packages_best_effort:
  - artha
  - audacity
  - autokey-gtk
  - borgbackup
  - catdoc
  - clamav
  - clamav-update
  - dict-gcide
  - dict-wn
  - dictd
  - diffpdf
  - flatpak
  - gimp
  - git-lfs
  - gitk
  - gnome-clocks
  - gnome-commander
  - gnupg2
  - hplip
  - hplip-gui
  - keepassxc
  - libxslt
  - nemo
  - nemo-fileroller
  - nextcloud-client
  - obs-studio
  - openssh-clients
  - openssh-server
  - pdfarranger
  - sqlitebrowser
  - okular
  - perl-librdf
  - pinentry
  - poppler-utils
  - pwgen
  - R
  - python3-tkinter
  - recoll
  - ruby
  - rubygem-bundler
  - texlive-lang-german
  - texlive-latex-extra
  - texlive-xetex
  - texstudio
  - tldr
  - unifont-fonts
  - unrtf
  - untex
  - vim
  - wv
  - xournalpp
  - xsel
