---
chrome_extensions_enabled: true
chrome_extension_update_url: https://clients2.google.com/service/update2/crx
chrome_extension_policy_directory: /etc/opt/chrome/policies/managed
chrome_extension_policy_file: workstation-extensions.json

chrome_extension_native_packages:
  - keepassxc

chrome_extensions:
  - name: "Advanced URL Cleaner"
    id: lbicdpmpkmpfoiiinfgkbaknidgkhnbp
  - name: "AI Grammar Checker & Paraphraser – LanguageTool"
    id: oldceeleldhonbafppcapldpdifcinji
  - name: "Freedom – Website Blocker for Chrome"
    id: abdkjmofmjelgafcdffaimhgdgpagmop
  - name: "JSON Formatter"
    id: bcjindcccaagfpapjjmafapmmgkkhgoa
  - name: "KeePassXC-Browser"
    id: oboonakemofpalcgghocfoadofidjkkk
  - name: "Obsidian Web Clipper"
    id: cnjifjpddelmedmihgijeibhnjfabmlf
  - name: "Unpaywall"
    id: iplffkdpngmdjhlpjmppncnlhomiipha
  - name: "Google Scholar Button"
    id: ldipcbpaocekfooobnbcddclnhejkcpn
  - name: "Vimium"
    id: dbepggeogbaibhgnhhndojpepiihcmeb
  - name: "Zotero Connector"
    id: ekhagklcjbdpajgpjgmbionohlpdbjgc
