---
vscode_repo_name: "vscode"
vscode_rpm_package: "code"
vscode_flatpak_id: "com.visualstudio.code"
vscode_rpm_desktop_id: "code.desktop"
vscode_flatpak_desktop_id: "com.visualstudio.code.desktop"
vscode_quarto_mime_type: "application/x-quarto"

vscode_mime_types:
  - text/plain
  - text/markdown
  - text/x-python
  - "{{ vscode_quarto_mime_type }}"

vscode_extensions:
  - ms-python.python
  - ms-toolsai.jupyter
  - ms-vscode.makefile-tools
  - ms-azuretools.vscode-docker
  - eamodio.gitlens
  - streetsidesoftware.code-spell-checker
  - yzhang.markdown-all-in-one
  - davidanson.vscode-markdownlint
  - davidlday.languagetool-linter
  - quarto.quarto
  - telesoho.vscode-markdown-paste-image
  - redhat.vscode-yaml
  - tamasfe.even-better-toml
  - esbenp.prettier-vscode

vscode_user_config_dirs:
  - "{{ target_home }}/.config/Code/User"
  - "{{ target_home }}/.var/app/com.visualstudio.code/config/Code/User"

vscode_settings:
  "workbench.startupEditor": "none"
  "workbench.welcomePage.walkthroughs.openOnInstall": false
  "workbench.tips.enabled": false
  "update.showReleaseNotes": false
  "telemetry.telemetryLevel": "off"
  "workbench.editor.enablePreview": false
  "files.trimTrailingWhitespace": true
  "editor.formatOnSave": true
  "MarkdownPaste.path": "${fileDirname}/images"
  "MarkdownPaste.silence": false
  "languageToolLinter.serviceType": "external"
  "languageToolLinter.external.url": "http://localhost:8081"
  "editor.trimAutoWhitespace": true
  "[markdown]":
    "editor.trimAutoWhitespace": false
  "[jupyter]":
    "editor.trimAutoWhitespace": false

vscode_keybindings:
  - key: "ctrl+pageup"
    command: "-quarto.goToPreviousCell"
    when: "editorTextFocus && editorLangId == 'quarto'"
  - key: "ctrl+pagedown"
    command: "-quarto.goToNextCell"
    when: "editorTextFocus && editorLangId == 'quarto'"
  - key: "ctrl+pageup"
    command: "workbench.action.previousEditor"
  - key: "ctrl+pagedown"
    command: "workbench.action.nextEditor"
