project:
  type: website

bibliography: references.bib

website:
  title: "workstation-setup"
  favicon: favicon.png
  repo-url: https://github.com/fs-ise/workstation-setup
  repo-subdir: docs
  repo-actions: [edit, issue]

  sidebar:
    logo: logo.png

    contents:
      - href: index.qmd
        text: Home

      - section: New machine
        contents:
          - install_os.qmd
          - install_software.qmd
          - restore.qmd

      - section: Day-to-day operations
        contents:
          - update_software.qmd
          - backup.qmd

      - section: Configuration
        contents:
          - baseline.qmd
          - veracrypt.qmd
          - docker.qmd
          - thunderbird.qmd
          - keepassxc.qmd
          - chrome.qmd
          - vscode.qmd
          - languagetool.qmd
          - teams.qmd
          - virtualbox.qmd
          - latex.qmd
          - quarto.qmd
          - r.qmd
          - rstudio.qmd
          - obsidian.qmd
          - ocr.qmd
          - grobid.qmd
          - llm.qmd

      - section: Reference
        contents:
          - repo_structure.qmd
          - principles.qmd
          - troubleshooting.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    mermaid:
      theme: neutral
    css: styles.css
    toc: false
    grid:
      sidebar-width: 280px
      body-width: 1000px
      margin-width: 280px
      gutter-width: 1.5rem
