---
- name: Decide whether VeraCrypt needs installation
  ansible.builtin.set_fact:
    veracrypt_install_required: >-
      {{ veracrypt_installed.rc != 0 or
         veracrypt_version_comparison.rc != 0 }}
