---
- name: Lab stack on Fedora
  hosts: local
  become: true

  vars:
    target_user: "{{ ansible_facts['env'].get('SUDO_USER', ansible_facts['user_id']) }}"
    target_home: "{{ ansible_facts['env'].get('HOME', lookup('ansible.builtin.env', 'HOME')) if ansible_facts['env'].get('SUDO_USER') is none else '/home/' ~ target_user }}"

  roles:
    - role: baseline  # should include packages (except for those needed in the following roles)
      tags: [baseline]

    - role: ocrmypdf
      tags: [ocr]

    - role: virtualbox
      tags: [virtualbox]

    - role: docker
      tags: [docker]

    - role: grobid
      tags: [grobid]

    - role: languagetool
      tags: [languagetool]

    - role: quarto
      tags: [quarto]

    - role: chrome
      tags: [chrome]

    - role: vscode
      tags: [vscode]

    - role: teams_for_linux
      tags: [teams]

    - role: thunderbird
      tags: [thunderbird]

    - role: desktop_gnome
      tags: [desktop]
